const keys = ['historyTitle','historyDescription','backToChat','taskStatus','historyAll','statusQueued','statusRunning','statusFailed','statusSucceeded','statusWaiting','statusCancelled','statusExpired','historyEmpty','historyNoMatch','mediaAudio','mediaVideo','taskId','createdTime','queuedTime','startedTime','completedTime','originalTask','resultUnavailable'];
const values = {
 en:['Task history','Your submitted video and audio translations. Status updates automatically.','Back to conversation','Status','All','Queued','In progress','Error','Completed','Waiting','Cancelled','Expired','No tasks yet. Confirm a translation to create your first task.','No tasks with this status.','Audio','Video','Task ID','Created','Queued','Started','Finished','Original task','The result is no longer available. The task record is retained.'],
 zh:['任务历史','查看已提交的视频和音频译制任务，状态自动更新。','返回对话','状态','全部','排队中','进行中','错误','已完成','待处理','已取消','已过期','还没有任务。确认开始译制后，任务会记录在这里。','没有这个状态的任务。','音频','视频','任务编号','创建时间','入队时间','开始时间','结束时间','原任务','结果文件已不可下载，任务记录仍保留。'],
 fr:['Historique des tâches','Vos traductions vidéo et audio. Les états sont mis à jour automatiquement.','Retour à la conversation','État','Tout','En attente','En cours','Erreur','Terminé','À traiter','Annulé','Expiré','Aucune tâche. Confirmez une traduction pour commencer.','Aucune tâche dans cet état.','Audio','Vidéo','Identifiant','Création','Mise en file','Début','Fin','Tâche initiale','Le résultat est indisponible. La tâche reste dans l’historique.'],
 es:['Historial de tareas','Tus traducciones de vídeo y audio. Los estados se actualizan automáticamente.','Volver a la conversación','Estado','Todas','En cola','En curso','Error','Completada','Pendiente','Cancelada','Caducada','Aún no hay tareas. Confirma una traducción para empezar.','No hay tareas con este estado.','Audio','Vídeo','ID de tarea','Creación','Entrada en cola','Inicio','Finalización','Tarea original','El resultado ya no está disponible. El registro se conserva.'],
 de:['Aufgabenverlauf','Deine Video- und Audioübersetzungen. Der Status wird automatisch aktualisiert.','Zurück zum Gespräch','Status','Alle','In Warteschlange','In Bearbeitung','Fehler','Abgeschlossen','Ausstehend','Abgebrochen','Abgelaufen','Noch keine Aufgaben. Bestätige eine Übersetzung, um zu beginnen.','Keine Aufgaben mit diesem Status.','Audio','Video','Aufgaben-ID','Erstellt','Eingereiht','Gestartet','Beendet','Ursprüngliche Aufgabe','Das Ergebnis ist nicht mehr verfügbar. Der Eintrag bleibt erhalten.'],
 ja:['タスク履歴','送信した動画・音声の翻訳タスク。状態は自動で更新されます。','会話に戻る','状態','すべて','待機中','処理中','エラー','完了','対応待ち','キャンセル済み','期限切れ','タスクはまだありません。翻訳の開始を確定すると記録されます。','この状態のタスクはありません。','音声','動画','タスクID','作成日時','受付日時','開始日時','終了日時','元のタスク','結果ファイルは利用できません。タスクの記録は保持されています。'],
 ko:['작업 기록','제출한 동영상 및 오디오 번역 작업입니다. 상태가 자동으로 갱신됩니다.','대화로 돌아가기','상태','전체','대기열','진행 중','오류','완료','처리 대기','취소됨','만료됨','아직 작업이 없습니다. 번역 시작을 확인하면 여기에 기록됩니다.','이 상태의 작업이 없습니다.','오디오','동영상','작업 ID','생성 시간','대기열 등록','시작 시간','종료 시간','원래 작업','결과 파일을 사용할 수 없습니다. 작업 기록은 보관됩니다.'],
 pt:['Histórico de tarefas','As suas traduções de vídeo e áudio. Os estados são atualizados automaticamente.','Voltar à conversa','Estado','Todas','Na fila','Em curso','Erro','Concluída','Pendente','Cancelada','Expirada','Ainda não há tarefas. Confirme uma tradução para começar.','Não há tarefas com este estado.','Áudio','Vídeo','ID da tarefa','Criação','Entrada na fila','Início','Conclusão','Tarefa original','O resultado já não está disponível. O registo da tarefa é mantido.'],
};
export const historyCopy = Object.fromEntries(Object.entries(values).map(([locale, entries]) => [locale,Object.fromEntries(keys.map((key,index) => [key,entries[index]]))]));
